# -------------------------------------------------------
# app/core/companies.py
# Danh mục toàn bộ đối tác doanh nghiệp tuyển dụng từ Việc 3 Miền
# -------------------------------------------------------
from typing import List

ALL_PARTNER_COMPANIES: List[str] = [
    "LUXSHARE ICT BẮC GIANG",
    "HỒNG HẢI ( FOXCONN )",
    "QUANTA",
    "GOERTEK VIỆT NAM",
    "LENS  VIỆT NAM",
    "PEGATRON VIỆT NAM",
    "WISTRON INFOCOMM HÀ NAM",
    "LUXSHARE ICT NGHỆ AN",
    "SẢN XUẤT COOLER MASTER (VIETNAM)",
    "YUZHAN VIỆT NAM",
    "AAC",
    "AAC TECHNOLOGIES",
    "ADVANCE FILM MATERIAL",
    "ALMUSTECH",
    "AMTRAN",
    "AUO",
    "AVC VIỆT NAM",
    "BIEL CRYSTAL",
    "BROTHER VIỆT NAM",
    "BUJEON VIỆT NAM ELECTRONICS",
    "CANON VIỆT NAM",
    "CELINK",
    "CHANG IL VINA",
    "CHUNQIU",
    "COLOR&COLOR",
    "CÔNG NHÂN MIỀN BẮC",
    "CÔNG NHÂN MIỀN TRUNG",
    "CÔNG TY  TNHH CRESYN HÀ NỘI",
    "CÔNG TY BẢO VỆ TRƯỜNG THÀNH TISTCO",
    "CÔNG NGHỆ THÔNG TIN 3T",
    "tư vấn đầu tư GTV",
    "CÔNG TY ĐIỆN TỬ BYD",
    "CÔNG TY MAY ANNAM",
    "ADTEK (VIỆT NAM)",
    "AMPHENOL COMMUNICATION ELECTRONICS VIỆT NAM",
    "COMPAL (VIỆT NAM)",
    "CÔNG NGHIỆP CHÍNH XÁC GOERTEK VINA",
    "DESAY BATTERY VINA",
    "FU WING INTERCONNECT TECHNOLOGY",
    "INNOVATION TƯƠNG LAI VIỆT NAM",
    "INST MAGNETIC NEW MATERIALS VIETNAM",
    "NĂNG LƯỢNG VÀ LINH KIỆN EV FOXCONN (QUẢNG NINH)",
    "NEWFACE OPTOELECTRONICS (VIỆT NAM)",
    "SẢN XUẤT XỐP NHỰA VÀ NHỰA THÁI HÀ",
    "TM SẢN XUẤT THÀNH NGHĨA",
    "UNIVERSAL SCIENTIFIC INDUSTRIAL VIỆT NAM",
    "WNC Việt Nam (WISTRON NEWEB CORPORATION)",
    "Data Cộng tác viên (CTV)",
    "DELI VIỆT NAM",
    "DIAMOND & ZEBRA ELECTRIC",
    "DREAMTECH",
    "EVERWIN",
    "FOXCONN AB",
    "FULIAN",
    "FUSHAN TECHNOLOGY VIỆT NAM",
    "G&G VINA TECH",
    "GEMTEK",
    "GEVOTAI VIỆT NAM",
    "GIGALANE",
    "GỖ MINH LONG",
    "HAEWON VINA",
    "HONDA VIỆT NAM",
    "HOSIDEN VIỆT NAM",
    "HYOSUNG",
    "ITM SEMICONDUCTOR VIETNAM",
    "J-TECH VINA",
    "JASAN VN",
    "JMC Việt Nam",
    "JMT VN",
    "KIM TƯỜNG NGUYÊN",
    "LANCER OPTICAL VN CO., LTD",
    "LG DISPLAY HẢI PHÒNG",
    "LingYi",
    "LITEON",
    "MYS GROUP VIETNAM",
    "NANO TECHNOLOGIES",
    "NEW WING BẮC GIANG",
    "NEWEB VIỆT NAM",
    "NGỌC SƠN BAMBOO AND RATTAN ENTERPRISE",
    "NITTO VIỆT NAM",
    "NOROO VINA",
    "QISDA VIỆT NAM",
    "REGINA MIRACLE",
    "RISUNTEK VN",
    "RR DONNELLEY",
    "SAMKWANG VINA",
    "SHINWON",
    "SHINWON EBENZER HÀ NỘI",
    "SIFLEX VIỆT NAM",
    "SOLAMODA VIỆT NAM",
    "SUMI VIỆT NAM",
    "SUMIDENSO VIỆT NAM",
    "SUNNY AUTOMOTIVE",
    "SYNOPEX",
    "TECHCOMBANK",
    "TOTO VIỆT NAM",
    "TREND POWER TECHNOLOGY",
    "VINA SOLAR TECHNOLOGY",
    "VINES",
    "VINFAST",
    "VITALINK",
    "VNPOST BÌNH DƯƠNG",
    "VPBANK SMBC",
    "WELL KING",
    "WK INTERNATIONAL",
    "WONJIN 2",
    "WOOYANG VINA II",
    "XINHAO VN",
    "YS VINA",
    "GAOJIA OPTOELECTRONIC TECHNOLOGY VIỆT NAM"
]

MAJOR_INDUSTRIAL_PARKS: List[str] = [
    "Quang Châu",
    "Vân Trung",
    "Quế Võ",
    "Quế Võ 2",
    "Quế Võ 3",
    "Đình Trám",
    "Hòa Phú",
    "VSIP Bắc Ninh",
    "VSIP Hải Phòng",
    "VSIP Nghệ An",
    "Yên Phong",
    "Yên Phong II",
    "Đại Đồng - Hoàn Sơn",
    "Tiên Sơn",
    "Đồng Văn II",
    "Đồng Văn III",
    "Đồng Văn IV",
    "Khai Quang",
    "Thăng Long II",
    "Nội Hoàng",
    "Tràng Duệ",
    "Đình Vũ - Cát Hải",
    "Deep C 2A",
    "Deep C 2B",
    "WHA Nghệ An",
    "Nhơn Trạch 5",
    "Thuận Thành 3",
    "Bảo Minh",
]

def get_companies_prompt_string() -> str:
    """Trả về chuỗi danh sách các doanh nghiệp đối tác để tiêm vào Prompt."""
    return ", ".join(ALL_PARTNER_COMPANIES)

def get_industrial_parks_prompt_string() -> str:
    """Trả về chuỗi danh sách các khu công nghiệp trọng điểm để tiêm vào Prompt."""
    return ", ".join(MAJOR_INDUSTRIAL_PARKS)
